// AUTO-GENERATED by scripts/run-calibrate.mjs — do not edit by hand.
// Run `npm run calibrate` to regenerate. Measured against the real
// drawDigit algorithm via Playwright + headless Chromium.
//
// Sample sizes used: [200,320,460,620,780]
// Generated: 2026-07-23T19:07:05.114Z

export interface BakedCalibration {
  font: string;
  /** dotsPerPixel[d] aggregated across sample sizes, biased toward large sizes. */
  dotsPerPixel: number[];
  /** perSize[d] = raw per-size measurements for digit d, ordered small → large. */
  perSize: { size: number; letterWidth: number; placed: number; dotsPerPixel: number }[][];
}

export const BAKED_CALIBRATIONS: BakedCalibration[] = [
  {
    "font": "Comic Sans MS",
    "dotsPerPixel": [
      0.0019572689106349167,
      0.001490201091626596,
      0.0020670835447769995,
      0.001940180465805563,
      0.001408482120743621,
      0.0023458733924774356,
      0.0020242971007086853,
      0.0011196893639691984,
      0.002737728673036857,
      0.002217310625753538
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 64,
          "dotsPerPixel": 0.0026666666666666666
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 146,
          "dotsPerPixel": 0.002376302083333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 236,
          "dotsPerPixel": 0.0018588531821045998
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 457,
          "dotsPerPixel": 0.0019814429413805065
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 616,
          "dotsPerPixel": 0.0016874863028709182
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 43,
          "dotsPerPixel": 0.0017916666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 103,
          "dotsPerPixel": 0.0016764322916666666
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 205,
          "dotsPerPixel": 0.0016146817895400126
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 337,
          "dotsPerPixel": 0.001461151578217135
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 476,
          "dotsPerPixel": 0.0013039666885820732
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 76,
          "dotsPerPixel": 0.0031666666666666666
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 163,
          "dotsPerPixel": 0.0026529947916666668
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 259,
          "dotsPerPixel": 0.002040012602394455
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 437,
          "dotsPerPixel": 0.0018947277141866112
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 645,
          "dotsPerPixel": 0.0017669296515450362
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 74,
          "dotsPerPixel": 0.0030833333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 120,
          "dotsPerPixel": 0.001953125
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 264,
          "dotsPerPixel": 0.0020793950850661624
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 417,
          "dotsPerPixel": 0.001808012486992716
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 631,
          "dotsPerPixel": 0.0017285776901161517
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 46,
          "dotsPerPixel": 0.0019166666666666666
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 101,
          "dotsPerPixel": 0.0016438802083333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 172,
          "dotsPerPixel": 0.0013547574039067423
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 341,
          "dotsPerPixel": 0.001478494623655914
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 434,
          "dotsPerPixel": 0.0011889108042954196
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 72,
          "dotsPerPixel": 0.003
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 150,
          "dotsPerPixel": 0.00244140625
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 304,
          "dotsPerPixel": 0.0023944549464398235
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 560,
          "dotsPerPixel": 0.002428026361429067
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 760,
          "dotsPerPixel": 0.0020819636204251588
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 71,
          "dotsPerPixel": 0.002958333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 150,
          "dotsPerPixel": 0.00244140625
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 251,
          "dotsPerPixel": 0.001977000630119723
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 471,
          "dotsPerPixel": 0.002042143600416233
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 615,
          "dotsPerPixel": 0.0016847468770545694
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 40,
          "dotsPerPixel": 0.0016666666666666668
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 71,
          "dotsPerPixel": 0.0011555989583333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 149,
          "dotsPerPixel": 0.0011735979836168871
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 277,
          "dotsPerPixel": 0.0012010058966354493
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 328,
          "dotsPerPixel": 0.000898531667762437
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 93,
          "dotsPerPixel": 0.003875
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 176,
          "dotsPerPixel": 0.002864583333333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 375,
          "dotsPerPixel": 0.002953686200378072
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 620,
          "dotsPerPixel": 0.002688172043010753
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 865,
          "dotsPerPixel": 0.002369603331141793
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 84,
          "dotsPerPixel": 0.0035
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 149,
          "dotsPerPixel": 0.0024251302083333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 264,
          "dotsPerPixel": 0.0020793950850661624
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 519,
          "dotsPerPixel": 0.002250260145681582
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 706,
          "dotsPerPixel": 0.0019340346263423186
        }
      ]
    ]
  },
  {
    "font": "Arial",
    "dotsPerPixel": [
      0.0019869161537805656,
      0.001081682832506676,
      0.0018134356809823662,
      0.0017843601918085732,
      0.00169082574242631,
      0.0019640798447306284,
      0.002244600475871092,
      0.0011851291333764109,
      0.0022199059110153845,
      0.0022549087085247644
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 62,
          "dotsPerPixel": 0.0025833333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 142,
          "dotsPerPixel": 0.0023111979166666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 280,
          "dotsPerPixel": 0.002205419029615627
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 420,
          "dotsPerPixel": 0.0018210197710718003
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 635,
          "dotsPerPixel": 0.0017395353933815471
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 37,
          "dotsPerPixel": 0.0015416666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 79,
          "dotsPerPixel": 0.0012858072916666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 123,
          "dotsPerPixel": 0.0009688090737240075
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 252,
          "dotsPerPixel": 0.00109261186264308
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 353,
          "dotsPerPixel": 0.0009670173131711593
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 57,
          "dotsPerPixel": 0.002375
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 134,
          "dotsPerPixel": 0.0021809895833333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 234,
          "dotsPerPixel": 0.0018431001890359168
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 426,
          "dotsPerPixel": 0.0018470343392299688
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 551,
          "dotsPerPixel": 0.0015094236248082403
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 63,
          "dotsPerPixel": 0.002625
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 120,
          "dotsPerPixel": 0.001953125
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 230,
          "dotsPerPixel": 0.0018115942028985507
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 400,
          "dotsPerPixel": 0.001734304543877905
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 574,
          "dotsPerPixel": 0.0015724304185842648
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 57,
          "dotsPerPixel": 0.002375
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 127,
          "dotsPerPixel": 0.0020670572916666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 227,
          "dotsPerPixel": 0.0017879647132955261
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 345,
          "dotsPerPixel": 0.001495837669094693
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 548,
          "dotsPerPixel": 0.0015012053473591935
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 66,
          "dotsPerPixel": 0.00275
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 141,
          "dotsPerPixel": 0.002294921875
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 281,
          "dotsPerPixel": 0.0022132955261499683
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 403,
          "dotsPerPixel": 0.0017473118279569893
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 620,
          "dotsPerPixel": 0.0016984440061363138
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 71,
          "dotsPerPixel": 0.002958333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 148,
          "dotsPerPixel": 0.0024088541666666668
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 282,
          "dotsPerPixel": 0.00222117202268431
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 473,
          "dotsPerPixel": 0.0020508151231356225
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 805,
          "dotsPerPixel": 0.002205237782160859
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 45,
          "dotsPerPixel": 0.001875
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 79,
          "dotsPerPixel": 0.0012858072916666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 186,
          "dotsPerPixel": 0.0014650283553875236
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 253,
          "dotsPerPixel": 0.0010969476240027748
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 332,
          "dotsPerPixel": 0.0009094893710278326
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 79,
          "dotsPerPixel": 0.0032916666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 169,
          "dotsPerPixel": 0.002750651041666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 267,
          "dotsPerPixel": 0.002103024574669187
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 494,
          "dotsPerPixel": 0.0021418661116892126
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 703,
          "dotsPerPixel": 0.001925816348893272
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 62,
          "dotsPerPixel": 0.0025833333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 159,
          "dotsPerPixel": 0.002587890625
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 287,
          "dotsPerPixel": 0.0022605545053560176
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 544,
          "dotsPerPixel": 0.0023586541796739506
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 719,
          "dotsPerPixel": 0.001969647161954854
        }
      ]
    ]
  },
  {
    "font": "Georgia",
    "dotsPerPixel": [
      0.0014979770901130147,
      0.0009616736216775341,
      0.0014754529137315797,
      0.0014664326562009917,
      0.001266734068325146,
      0.001608494447558959,
      0.001487421719957143,
      0.0009246882502480676,
      0.0020802934421481965,
      0.0016360440516921435
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 44,
          "dotsPerPixel": 0.0018333333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 116,
          "dotsPerPixel": 0.0018880208333333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 208,
          "dotsPerPixel": 0.0016383112791430372
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 331,
          "dotsPerPixel": 0.0014351370100589664
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 453,
          "dotsPerPixel": 0.0012409598948060487
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 31,
          "dotsPerPixel": 0.0012916666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 63,
          "dotsPerPixel": 0.001025390625
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 111,
          "dotsPerPixel": 0.0008742911153119092
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 209,
          "dotsPerPixel": 0.0009061741241762054
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 353,
          "dotsPerPixel": 0.0009670173131711593
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 51,
          "dotsPerPixel": 0.002125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 105,
          "dotsPerPixel": 0.001708984375
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 202,
          "dotsPerPixel": 0.001591052299936988
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 333,
          "dotsPerPixel": 0.001443808532778356
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 441,
          "dotsPerPixel": 0.001208086785009862
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 56,
          "dotsPerPixel": 0.0023333333333333335
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 106,
          "dotsPerPixel": 0.0017252604166666666
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 171,
          "dotsPerPixel": 0.0013468809073724007
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 303,
          "dotsPerPixel": 0.001313735691987513
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 505,
          "dotsPerPixel": 0.001383410037256191
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 45,
          "dotsPerPixel": 0.001875
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 109,
          "dotsPerPixel": 0.0017740885416666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 153,
          "dotsPerPixel": 0.0012051039697542534
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 253,
          "dotsPerPixel": 0.0010969476240027748
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 407,
          "dotsPerPixel": 0.0011149463072539995
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 57,
          "dotsPerPixel": 0.002375
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 117,
          "dotsPerPixel": 0.001904296875
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 228,
          "dotsPerPixel": 0.0017958412098298677
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 322,
          "dotsPerPixel": 0.0013961151578217135
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 509,
          "dotsPerPixel": 0.0013943677405215866
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 60,
          "dotsPerPixel": 0.0025
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 88,
          "dotsPerPixel": 0.0014322916666666666
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 201,
          "dotsPerPixel": 0.0015831758034026465
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 355,
          "dotsPerPixel": 0.0015391952826916406
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 441,
          "dotsPerPixel": 0.001208086785009862
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 31,
          "dotsPerPixel": 0.0012916666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 62,
          "dotsPerPixel": 0.0010091145833333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 119,
          "dotsPerPixel": 0.0009373030875866415
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 198,
          "dotsPerPixel": 0.0008584807492195629
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 315,
          "dotsPerPixel": 0.0008629191321499013
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 72,
          "dotsPerPixel": 0.003
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 156,
          "dotsPerPixel": 0.0025390625
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 256,
          "dotsPerPixel": 0.0020163831127914303
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 480,
          "dotsPerPixel": 0.002081165452653486
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 639,
          "dotsPerPixel": 0.0017504930966469427
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 56,
          "dotsPerPixel": 0.0023333333333333335
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 112,
          "dotsPerPixel": 0.0018229166666666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 222,
          "dotsPerPixel": 0.0017485822306238185
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 365,
          "dotsPerPixel": 0.0015825528962885884
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 510,
          "dotsPerPixel": 0.0013971071663379355
        }
      ]
    ]
  },
  {
    "font": "Courier New",
    "dotsPerPixel": [
      0.0008204618230968353,
      0.0005339055614211744,
      0.0006954757253672353,
      0.0006065693525098905,
      0.0008193279864436876,
      0.000616235708441528,
      0.0008489852990429997,
      0.0004064805965259199,
      0.0009945843570443925,
      0.0008932761122552059
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 38,
          "dotsPerPixel": 0.0015833333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 49,
          "dotsPerPixel": 0.0007975260416666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 114,
          "dotsPerPixel": 0.0008979206049149339
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 157,
          "dotsPerPixel": 0.0006807145334720777
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 271,
          "dotsPerPixel": 0.0007423843962305501
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 23,
          "dotsPerPixel": 0.0009583333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 50,
          "dotsPerPixel": 0.0008138020833333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 55,
          "dotsPerPixel": 0.00043320730938878387
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 109,
          "dotsPerPixel": 0.0004725979882067291
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 163,
          "dotsPerPixel": 0.0004465264080648696
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 32,
          "dotsPerPixel": 0.0013333333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 62,
          "dotsPerPixel": 0.0010091145833333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 80,
          "dotsPerPixel": 0.000630119722747322
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 150,
          "dotsPerPixel": 0.0006503642039542144
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 189,
          "dotsPerPixel": 0.0005177514792899408
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 27,
          "dotsPerPixel": 0.001125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 56,
          "dotsPerPixel": 0.0009114583333333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 52,
          "dotsPerPixel": 0.0004095778197857593
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 129,
          "dotsPerPixel": 0.0005593132154006244
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 196,
          "dotsPerPixel": 0.0005369274600043831
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 34,
          "dotsPerPixel": 0.0014166666666666668
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 58,
          "dotsPerPixel": 0.0009440104166666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 96,
          "dotsPerPixel": 0.0007561436672967864
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 178,
          "dotsPerPixel": 0.0007717655220256677
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 265,
          "dotsPerPixel": 0.0007259478413324567
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 32,
          "dotsPerPixel": 0.0013333333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 49,
          "dotsPerPixel": 0.0007975260416666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 83,
          "dotsPerPixel": 0.0006537492123503465
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 131,
          "dotsPerPixel": 0.0005679847381200139
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 152,
          "dotsPerPixel": 0.00041639272408503175
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 32,
          "dotsPerPixel": 0.0013333333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 65,
          "dotsPerPixel": 0.0010579427083333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 136,
          "dotsPerPixel": 0.0010712035286704474
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 204,
          "dotsPerPixel": 0.0008844953173777315
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 185,
          "dotsPerPixel": 0.0005067937760245453
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 21,
          "dotsPerPixel": 0.000875
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 25,
          "dotsPerPixel": 0.0004069010416666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 63,
          "dotsPerPixel": 0.0004962192816635161
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 72,
          "dotsPerPixel": 0.0003121748178980229
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 122,
          "dotsPerPixel": 0.00033420994959456495
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 39,
          "dotsPerPixel": 0.001625
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 72,
          "dotsPerPixel": 0.001171875
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 121,
          "dotsPerPixel": 0.0009530560806553245
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 213,
          "dotsPerPixel": 0.0009235171696149844
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 321,
          "dotsPerPixel": 0.0008793556870479947
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 28,
          "dotsPerPixel": 0.0011666666666666668
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 67,
          "dotsPerPixel": 0.0010904947916666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 123,
          "dotsPerPixel": 0.0009688090737240075
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 179,
          "dotsPerPixel": 0.0007761012833853624
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 295,
          "dotsPerPixel": 0.0008081306158229235
        }
      ]
    ]
  },
  {
    "font": "Impact",
    "dotsPerPixel": [
      0.0046314547848858014,
      0.002545738465346219,
      0.0036363321039688274,
      0.004106449169083602,
      0.0038060225946365675,
      0.00425515913871544,
      0.004617500337002591,
      0.0027011114068745622,
      0.004986971192027433,
      0.004672781640455687
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 137,
          "dotsPerPixel": 0.0057083333333333335
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 347,
          "dotsPerPixel": 0.005647786458333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 618,
          "dotsPerPixel": 0.004867674858223063
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 1016,
          "dotsPerPixel": 0.004405133541449878
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1478,
          "dotsPerPixel": 0.004048871356563664
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 75,
          "dotsPerPixel": 0.003125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 180,
          "dotsPerPixel": 0.0029296875
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 338,
          "dotsPerPixel": 0.0026622558286074354
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 563,
          "dotsPerPixel": 0.0024410336455081513
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 836,
          "dotsPerPixel": 0.002290159982467675
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 107,
          "dotsPerPixel": 0.004458333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 229,
          "dotsPerPixel": 0.003727213541666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 486,
          "dotsPerPixel": 0.0038279773156899813
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 808,
          "dotsPerPixel": 0.003503295178633368
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1251,
          "dotsPerPixel": 0.0034270216962524656
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 123,
          "dotsPerPixel": 0.005125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 278,
          "dotsPerPixel": 0.004524739583333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 540,
          "dotsPerPixel": 0.004253308128544423
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 904,
          "dotsPerPixel": 0.003919528269164065
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1386,
          "dotsPerPixel": 0.003796844181459566
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 122,
          "dotsPerPixel": 0.005083333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 233,
          "dotsPerPixel": 0.0037923177083333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 556,
          "dotsPerPixel": 0.004379332073093888
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 804,
          "dotsPerPixel": 0.003485952133194589
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1266,
          "dotsPerPixel": 0.003468113083497699
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 110,
          "dotsPerPixel": 0.004583333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 299,
          "dotsPerPixel": 0.004866536458333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 576,
          "dotsPerPixel": 0.004536862003780718
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 928,
          "dotsPerPixel": 0.004023586541796739
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1446,
          "dotsPerPixel": 0.0039612097304405
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 137,
          "dotsPerPixel": 0.0057083333333333335
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 331,
          "dotsPerPixel": 0.005387369791666667
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 602,
          "dotsPerPixel": 0.004741650913673598
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 991,
          "dotsPerPixel": 0.004296739507457509
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1560,
          "dotsPerPixel": 0.004273504273504274
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 82,
          "dotsPerPixel": 0.003416666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 178,
          "dotsPerPixel": 0.0028971354166666668
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 343,
          "dotsPerPixel": 0.002701638311279143
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 593,
          "dotsPerPixel": 0.002571106486298994
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 943,
          "dotsPerPixel": 0.0025832785448170062
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 147,
          "dotsPerPixel": 0.006125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 322,
          "dotsPerPixel": 0.005240885416666666
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 674,
          "dotsPerPixel": 0.005308758664146188
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 1045,
          "dotsPerPixel": 0.0045308706208810265
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1763,
          "dotsPerPixel": 0.004829607714223099
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 141,
          "dotsPerPixel": 0.005875
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 299,
          "dotsPerPixel": 0.004866536458333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 599,
          "dotsPerPixel": 0.004718021424070573
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 997,
          "dotsPerPixel": 0.0043227540756156785
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 1682,
          "dotsPerPixel": 0.004607714223098839
        }
      ]
    ]
  },
  {
    "font": "Verdana",
    "dotsPerPixel": [
      0.0022934442673467575,
      0.001313630612725609,
      0.0016892374003845156,
      0.0017139527974727256,
      0.0014723184006121112,
      0.0019265862648381673,
      0.0020207917992896398,
      0.0010877413072329387,
      0.0023344422537348117,
      0.002179916261088736
    ],
    "perSize": [
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 78,
          "dotsPerPixel": 0.00325
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 160,
          "dotsPerPixel": 0.0026041666666666665
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 296,
          "dotsPerPixel": 0.0023314429741650915
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 490,
          "dotsPerPixel": 0.0021245230662504336
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 763,
          "dotsPerPixel": 0.0020901818978742055
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 44,
          "dotsPerPixel": 0.0018333333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 83,
          "dotsPerPixel": 0.0013509114583333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 185,
          "dotsPerPixel": 0.0014571518588531822
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 283,
          "dotsPerPixel": 0.0012270204647936178
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 430,
          "dotsPerPixel": 0.001177953101030024
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 61,
          "dotsPerPixel": 0.0025416666666666665
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 121,
          "dotsPerPixel": 0.0019694010416666666
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 198,
          "dotsPerPixel": 0.001559546313799622
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 384,
          "dotsPerPixel": 0.0016649323621227888
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 549,
          "dotsPerPixel": 0.0015039447731755424
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 51,
          "dotsPerPixel": 0.002125
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 114,
          "dotsPerPixel": 0.00185546875
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 242,
          "dotsPerPixel": 0.001906112161310649
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 351,
          "dotsPerPixel": 0.0015218522372528616
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 589,
          "dotsPerPixel": 0.001613521805829498
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 49,
          "dotsPerPixel": 0.0020416666666666665
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 101,
          "dotsPerPixel": 0.0016438802083333333
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 183,
          "dotsPerPixel": 0.001441398865784499
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 329,
          "dotsPerPixel": 0.001426465487339577
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 491,
          "dotsPerPixel": 0.0013450580758273066
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 57,
          "dotsPerPixel": 0.002375
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 137,
          "dotsPerPixel": 0.0022298177083333332
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 244,
          "dotsPerPixel": 0.001921865154379332
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 428,
          "dotsPerPixel": 0.0018557058619493583
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 648,
          "dotsPerPixel": 0.0017751479289940828
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 81,
          "dotsPerPixel": 0.003375
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 137,
          "dotsPerPixel": 0.0022298177083333332
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 283,
          "dotsPerPixel": 0.0022290485192186515
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 405,
          "dotsPerPixel": 0.0017559833506763788
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 640,
          "dotsPerPixel": 0.0017532325224632918
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 38,
          "dotsPerPixel": 0.0015833333333333333
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 81,
          "dotsPerPixel": 0.001318359375
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 144,
          "dotsPerPixel": 0.0011342155009451795
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 228,
          "dotsPerPixel": 0.0009885535900104059
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 346,
          "dotsPerPixel": 0.000947841332456717
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 80,
          "dotsPerPixel": 0.0033333333333333335
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 164,
          "dotsPerPixel": 0.0026692708333333334
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 307,
          "dotsPerPixel": 0.002418084436042848
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 495,
          "dotsPerPixel": 0.0021462018730489074
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 767,
          "dotsPerPixel": 0.0021011396011396013
        }
      ],
      [
        {
          "size": 200,
          "letterWidth": 120,
          "placed": 67,
          "dotsPerPixel": 0.0027916666666666667
        },
        {
          "size": 320,
          "letterWidth": 192,
          "placed": 137,
          "dotsPerPixel": 0.0022298177083333332
        },
        {
          "size": 460,
          "letterWidth": 276,
          "placed": 278,
          "dotsPerPixel": 0.002189666036546944
        },
        {
          "size": 620,
          "letterWidth": 372,
          "placed": 527,
          "dotsPerPixel": 0.00228494623655914
        },
        {
          "size": 780,
          "letterWidth": 468,
          "placed": 711,
          "dotsPerPixel": 0.0019477317554240632
        }
      ]
    ]
  }
];

/** Case-insensitive lookup. Returns null when no baked data exists for the font. */
export function findBakedCalibration(fontFamily: string): BakedCalibration | null {
  const key = fontFamily.toLowerCase();
  for (const c of BAKED_CALIBRATIONS) {
    if (c.font.toLowerCase() === key) return c;
  }
  return null;
}
